SAMPLES = ["TLE66_N","TLE66_T"]
DB = "/staging/leuven/stg_00079/teaching/hg38_9/chr9.fa" #database path
SNPEFF_JAR = "/lustre1/project/stg_00079/teaching/I0U19a_conda_2026/share/snpeff-5.4.0a-0/snpEff.jar"


rule all:
    input:
        tsv = "100.final/snps.annotated.tsv",
        sql_db = "150.db/snps.sqlite",
        fig1 = "160.figures/fig1_impact_severity.svg",
        fig2 = "160.figures/fig2_snp_quality_scores.svg"

#check the checksums and format of the fastq files 
rule checksum_fastq:
    input:
        expand("{sample}.fastq",sample=SAMPLES),
        md5 ="checksums.md5"
    output: 
        md5="validated/checksums_verified.flag"
    shell:
        """
        mkdir -p validated
        md5sum -c {input.md5}
        touch {output}
        """

#validate the if the files are indeed fastq format files
rule validate_fastq:
    input:
        fastq="{sample}.fastq",
        checksum="validated/checksums_verified.flag"
    output:
        "validated/{sample}.fastq.ok"
    shell:
        """
        head -n 4 {input.fastq} > /dev/null
        touch {output}
        """

#run the fastqc on each fastq file
rule run_fastqc:
    input:
        fastq="{sample}.fastq",
        check="validated/{sample}.fastq.ok"
    output:
        html="fastqc_output/{sample}_fastqc.html",
        zip="fastqc_output/{sample}_fastqc.zip"
    shell:
        """
        mkdir -p fastqc_output
        fastqc {input.fastq} -o fastqc_output
        """


#align reads
rule align_reads:
    input:
       fastq = "{sample}.fastq",
       check = "validated/{sample}.fastq.ok",
       fastqc = "fastqc_output/{sample}_fastqc.html"
    output:
        "bam_output/{sample}.bam"
    params:
        db = DB
    shell:
        """
        mkdir -p bam_output
        bwa mem {params.db} {input.fastq} | samtools sort -o {output} - 
        """

#validate if the files are indeed bam files
rule validate_bam:
    input:
        "bam_output/{sample}.bam"
    output:
        "validated/{sample}.bam.ok"
    shell:
        """
        samtools quickcheck {input}
        touch {output}
        """

#create indici
rule create_indici:
    input:
        bam="bam_output/{sample}.bam",
        check="validated/{sample}.bam.ok"
    output:
        "bam_output/{sample}.bam.bai"
    shell:
        """
        samtools index {input.bam}
        """


#SNP calling
rule snp_calling:
    input:
        expand("bam_output/{sample}.bam",sample=SAMPLES)
    output:
        "vcf/raw_snps.vcf"
    params:
        db = DB
    shell:
        """
        mkdir -p vcf
        bcftools mpileup -Ou -f {params.db} {input} | bcftools call -mv -Ov -o {output}
        """

# Validate the raw VCF before cleaning
rule validate_vcf:
    input:
        vcf = "vcf/raw_snps.vcf",
        ref = DB
    output:
        ok = "validated/raw_snps.vcf.ok",
        report = "vcf/raw_snps.validator_report.txt"
    shell:
        """
        bcftools view {input.vcf} > /dev/null
        bcftools stats {input.vcf} > {output.report}
        touch {output.ok}
        """
#SNP cleaning
rule snp_cleaning:
    input:
        vcf="vcf/raw_snps.vcf",
        check="validated/raw_snps.vcf.ok"
    output:
        "vcf/clean_snps.vcf"
    params:
        db=DB
    shell:
        """
        cat {input.vcf} \
        | vt decompose - \
        | vt normalize -n -r {params.db} - \
        | vt uniq - \
        | vt view -f "QUAL>20" -h - \
        > {output}
        """
#validation of the clean vcf files
rule validate_clean_vcf:
    input:
        vcf = "vcf/clean_snps.vcf",
        ref = DB
    output:
        ok = "validated/clean_snps.vcf.ok",
        report = "vcf/clean_snps.stats.txt"
    shell:
        """
        mkdir -p vcf
        bcftools view {input.vcf} > /dev/null
        bcftools stats {input.vcf} > {output.report}
        touch {output.ok}
        """
#SNP Annotation
rule snp_annotation:
    input:
        vcf="vcf/clean_snps.vcf",
        check="validated/clean_snps.vcf.ok"
    output:
        "vcf/annotated_snps.vcf"
    params:
        snpeff_jar=SNPEFF_JAR,
        db_path="/staging/leuven/stg_00079/teaching/snpeff_db"
    shell:
        """
        java -Xmx4g -jar {params.snpeff_jar} eff \
        -dataDir {params.db_path} \
        -v \
        hg38 {input.vcf} > {output}
        """

rule validate_annotated_vcf:
    input:
        vcf = "vcf/annotated_snps.vcf"
    output:
        ok = "validated/annotated_snps.vcf.ok",
        report = "vcf/annotated_snps.validator_report.txt"
    shell:
        """
        mkdir -p vcf
        echo "Checking ANN annotation presence..." > {output.report}
        
        # Directly grep the file to avoid the pipefail trap
        if grep -q "ANN=" {input.vcf}; then
            echo "ANN field found" >> {output.report}
        else
            echo "ERROR: No ANN field found" >> {output.report}
            exit 1
        fi
        
        touch {output.ok}
        """

#create the final annotated tsv
rule create_annotated_tsv:
    input:
        vcf="vcf/annotated_snps.vcf",
        check="validated/annotated_snps.vcf.ok"
    output:
        "100.final/snps.annotated.tsv"
    shell:
        """
        mkdir -p 100.final
        echo -e "CHROM\tPOS\tREF\tALT\tQUAL\tANN\tGT" > {output}
        bcftools query -f '%CHROM\t%POS\t%REF\t%ALT\t%QUAL\t%INFO/ANN\t[%GT]\n' \
        {input.vcf} >> {output}
        """

rule create_database:
    input:
        vcf = "vcf/annotated_snps.vcf"
    output:
        db = "150.db/snps.sqlite"
    shell:
        """
        python load_vcf_to_sqlite.py {input.vcf} {output.db}
        echo "Running DB queries"
        python run_queries.py {output.db}
        echo "Finished the queries"
        """
rule create_figures:
    input:
        db = "150.db/snps.sqlite"
    params:
        folder = "160.figures"
    output:
        
        fig1 = "160.figures/fig1_impact_severity.svg"
        fig2 = "160.figures/fig2_snp_quality_scores.svg"
    shell:
        """
        python visualization.py {input.db} {params.folder}
        """















