SAMPLES = ["TLE66_N","TLE66_T"]
DB = "/staging/leuven/stg_00079/teaching/hg38_9/chr9.fa" #database path
SNPEFF_JAR = "/lustre1/project/stg_00079/teaching/I0U19a_conda_2026/share/snpeff-5.4.0a-0/snpEff.jar"


rule all:
    input:
        expand("fastqc_output/{sample}_fastqc.html", sample=SAMPLES),
        expand("fastqc_output/{sample}_fastqc.zip", sample=SAMPLES),
        expand("bam_output/{sample}.bam", sample=SAMPLES),
        expand("bam_output/{sample}.bam.bai", sample=SAMPLES),
        "vcf/raw_snps.vcf",
        "vcf/clean_snps.vcf",
        "vcf/annotated_snps.vcf"


#check the checksums of the fastq files 
rule check_fastq_checksums:
    input:
        expand("data/{sample}.fastq",sample=SAMPLES),
        md5 ="data/checksums.md5"
    output: 
        "checksums_verified.flag"
    shell:
        """
        md5sum -c {input.md5}
        touch {output} 
        """

#run the fastqc on each fastq file
rule run_fastqc:
    input:
        expand("data/{sample}.fastq",sample=SAMPLES)
    output:
        expand("fastqc_output/{sample}_fastqc.html",sample=SAMPLES),
        expand("fastqc_output/{sample}_fastqc.zip",sample=SAMPLES)
    shell:
        """
        mkdir -p fastqc_output
        fastqc {input} -o fastqc_output
        """
#align reads
rule align_reads:
    input:
       "data/{sample}.fastq"
    output:
        "bam_output/{sample}.bam"
    params:
        db = DB
    shell:
        """
        mkdir -p bam_output
        bwa mem {params.db} {input} | samtools sort -o {output} - 
        """


#create indici
rule create_indici:
    input:
        "bam_output/{sample}.bam"
    output:
        "bam_output/{sample}.bam.bai"
    shell:
        "samtools index {input}"


#SNP calling
rule snp_calling:
    input:
        expand("bam_output/{sample}.bam",sample=SAMPLES)
    output:
        "vcf/raw_snps.vcf"
    params:
        db = DB
    shell:
        """
        mkdir -p vcf
        bcftools mpileup -Ou -f {params.db} {input} | bcftools call -mv -Ov -o {output}
        """

#SNP cleaning
rule snp_cleaning:
    input:
        "vcf/raw_snps.vcf"
    output:
        "vcf/clean_snps.vcf"
    params:
        db=DB
    shell:
        """
        cat {input} \
        | vt decompose - \
        | vt normalize -n -r {params.db} - \
        | vt uniq - \
        | vt view -f "QUAL>20" -h - \
        > {output}
        """



#SNP Annotation
rule snp_annotation:
    input:
        "vcf/clean_snps.vcf"
    output:
        "vcf/annotated_snps.vcf"
    params:
        snpeff_jar=SNPEFF_JAR
    shell:
        """
        java -Xmx4g -jar {params.snpeff_jar} eff hg19 -dataDir /staging/leuven/stg_00079/teaching/snpeff_db \
        {input} > {output}
        """













