SAMPLES = ['test1','test2']

rule all:
    input:
        "030.output/output.tsv"

rule create_tsv:
    input:
        expand("020.gc/{sample}.gc",sample=SAMPLES)
    output:
        "030.output/output.tsv"
    shell:
        """
        head -n 1 {input[0]} > {output}
        for f in {input}; do
            tail -n +2 $f >> {output}
        done
        """

rule calculate_gc:
    input:
        "{sample}.fa"
    output:
        "020.gc/{sample}.gc"
    shell:
        """
        export PATH=/lustre1/project/stg_00079/teaching/I0U19a_conda_2024/bin:$PATH
        python gc_calc.py '{input}' '{output}'
        """
