rule calculate_gc:
    input:
        "test1.fa",
        "test2.fa"
    output:
        "020.gc/test1.gc"
        "020.gc/test2.gc"
    shell:
        """
        python gc_calc.py 'test1.fa' '020.gc/test1.gc
         python gc_calc.py 'test2.fa' '020.gc/test2.gc'
        """
